#!/bin/sh
#
# /etc/init.d/nw_meta
#
# chkconfig: - 64 36
# description: PS Meta Collector
 
# Source init functions
. /etc/rc.d/init.d/functions
 
prog="psMetaCollector.py"
prefix="/afs/cern.ch/user/i/ivukotic/NetworkWeatherService/NetworkWeatherCollector"
exec_prefix="${prefix}"
prog_bin="${exec_prefix}/${prog}"
 
PIDFILE="/var/run/${prog}.pid"
 
start()
{
       [ -f $PIDFILE ] && echo "Already started" && exit
       echo -n $"Starting $prog: "
       nohup $prog_bin 2>&1 > /var/log/${prog}.log & echo $! > $PIDFILE
       daemon --pidfile $PIDFILE
       [ -f $PIDFILE ] && success $"$prog startup" || failure $"$prog startup"
       echo
}
 
stop()
{
       echo -n $"Shutting down $prog: "
       [ -f $PIDFILE ] && killproc -p `echo $PIDFILE` || success $"$prog shutdown"
       echo
}
 
status()
{
       if [ -f $PIDFILE ]; then
         kill -0 `cat $PIDFILE`
         if [ $? -eq 0 ]; then
           echo "$prog is running (pid `cat $PIDFILE`)"
           return 0
         else
           echo "process dead but pidfile exists"
           return 1
         fi
       else
         echo "$prog is stopped"
         return 3
       fi
}
 
case "$1" in
 
 start)
   start
 ;;
 
 stop)
   stop
 ;;
 
 status)
   status
 ;;
 
 restart)
   stop
   start
 ;;
 
 *)
   echo "Usage: $0 {start|stop|restart|status}"
 ;;
 
esac
